version: '3.2'
services:
  rails:
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
  nginx:
    build:
      cache_from:
        - ${DOCKER_CACHE}
      context: .
      dockerfile: docker/Dockerfile.nginx
    command: bash project_root/nginx_entry.sh
    environment:
      RAILS_HOST: rails
    ports:
      - "80:80"
    volumes_from:
      - rails:ro